version: 3

tasks:
  clear:
    desc: "Clear build artifacts"
    cmds:
      - rm -f ./data/cli/* ./data/rpc/* 2>/dev/null || true
      - mkdir -p ./data/cli ./data/rpc ./release

  check-git:
    silent: true
    cmds:
      - |
        if [ -z "$CI" ]; then
          git status --porcelain
        fi