version: 3

tasks:
  go:
    desc: "格式化 Go 代码"
    deps: [":base:clear"]
    cmds:
      - go fmt ./...

  check:
    desc: "使用 go vet 检查代码"
    deps: [":base:clear"]
    cmds:
      - go vet ./...

  all:
    desc: "格式化并检查所有代码"
    deps: [":base:clear"]
    cmds:
      - task: go
      - task: check